checkpoint_interval: 0
log_interval: 50
batch_size: 64
epochs: 50

lr: 0.001
scheduler: step
step_size: 10
eta_min: 0.0001
weight_decay: 0.0
gamma: 0.5
milestones: [5,15]

parallel: False
data:
  train_path: gigaword/dev/train.src.small.txt
  val_path:   gigaword/dev/valid.src.small.txt
  seq_len: 60
  stateful: False
  sos: True
  oovs: 10
vocab:
  vocab_path: gigaword/train.article.vocab.10K.txt
  size: 15000
  subword: False
  subword_path: xxxxxxxxxxxxxx
model:
  emb_size: 300
  embed_noise: 0.0
  embed_dropout: 0.2
  rnn_size: 1024
  rnn_layers: 2
  rnn_dropout: 0.5
  decode: True
  layer_norm: False
  tie_weights: True
  countdown: True
  pack: True
  clip: 1